name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:bookworm

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update -y
        apt-get install -y --no-install-recommends \
          cmake \
          clang-tidy \
          nginx \
          libwebsockets-dev \
          libfftw3-dev \
          libasound2-dev \
          build-essential 

    - name: Build
      run: |
        chmod +x compile.sh
        ./compile.sh 2>&1 | tee output.log
        
        if grep -q "error:" output.log; then
          echo "::error::Build failed due to errors in the build log" #Use of ::error::
          exit 1
        else
          echo "Build completed without errors."
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/

    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: output.log

  lint:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true

    steps:
    - name: Download build log
      uses: actions/download-artifact@v4
      with:
        name: build-log
        path: .

    - name: Check for warnings in the build log
      run: |
        cat output.log
        ! grep -q "warning:" output.log


  test:
    runs-on: ubuntu-latest
    container: debian:bookworm
    needs: build
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install test dependencies (if different or needed again)
      run: |
        apt-get update -y
        apt-get install -y --no-install-recommends \
          cmake \
          clang-tidy \
          nginx \
          libwebsockets-dev \
          libfftw3-dev \
          libasound2-dev \
          build-essential # Install make for tests too

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build
        path: build/

    - name: Run tests
      run: |
        chmod +x build/tests/*
        ctest --test-dir ./build
